//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.DataAccess.Mssql
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuario
    {
        public int usuarioID { get; set; }
        public string usuarioNome { get; set; }
        public string usuarioLogin { get; set; }
        public string usuarioSenha { get; set; }
    }
}
